name: Python package (install dependencies, test with pytest)

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest,ubuntu-latest]
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install pybind11
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test torch
      run: |
        python -c "import torch; print(torch.__version__)"
    - name: Compile kernel
      run: |
        echo $PYTHON
        python setup.py install
    - name: List files
      run: |
        ls -la
        pwd
    - name: Test with pytest
      run: |
        pytest
