name: Python package (install dependencies, test with pytest)

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6.15]

    steps:
    - uses: actions/checkout@v4
      with:
        node-version: '18.x'
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        node-version: '18.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install pybind11
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install -e .
    - name: List files
      run: |
        ls -la
        pwd
    - name: Test with pytest
      run: |
        pytest
